version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14  # Node.jsを含むDockerイメージ
    working_directory: ~/salesforce-ci  # 作業ディレクトリ
    environment:
      # Salesforce CLIのダウンロードURL
      DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    steps:
      - checkout  # GitHubリポジトリからコードを取得

      # Salesforce CLIをダウンロードしてインストール
      - run:
          name: Install Salesforce CLI
          command: |
            mkdir sfdx
            wget -O sfdx.tar.xz $DX_CLI_URL
            tar -xJf sfdx.tar.xz -C sfdx --strip-components 1
            ./sfdx/install
            sfdx --version  # インストール確認

      # Salesforce CLIでDev Hubに認証
      - run:
          name: Authenticate Dev Hub
          command: |
            echo $SFDC_SERVER_KEY > server.key
            sfdx auth:jwt:grant --clientid $SFDC_CLIENT_ID --jwtkeyfile server.key --username $SFDC_USERNAME --setdefaultdevhubusername

      # Scratch Orgを作成
      - run:
          name: Create Scratch Org
          command: |
            sfdx force:org:create -s -f config/project-scratch-def.json -a ci_scratch

      # ソースコードをScratch Orgにプッシュ
      - run:
          name: Push Source to Scratch Org
          command: |
            sfdx force:source:push -u ci_scratch

      # Apexテストを実行
      - run:
          name: Run Apex Tests
          command: |
            mkdir -p test-results
            sfdx force:apex:test:run -c -r junit -d test-results -u ci_scratch

      # テスト結果を保存
      - store_test_results:
          path: test-results

      # Scratch Orgを削除
      - run:
          name: Delete Scratch Org
          command: |
            sfdx force:org:delete -u ci_scratch -p

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
