version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14  # Node.jsを含むDockerイメージ
    working_directory: ~/ci_app
    steps:
      - checkout  # GitHubリポジトリからコードを取得

      # Salesforce CLIをnpmでインストール
      - run:
          name: Install Salesforce CLI via npm
          command: |
            npm install @salesforce/cli --global
            sf --version  # CLIバージョン確認

      # Dev Hubに認証
      - run:
          name: Authenticate Dev Hub
          command: |
            echo $SFDC_SERVER_KEY > server.key
            sf org login jwt --client-id $SFDC_CLIENT_ID --jwt-key-file server.key --username $SFDC_USERNAME --set-default-dev-hub

      # Scratch Orgを作成
      - run:
          name: Create Scratch Org
          command: |
            sf org create scratch --definition-file config/project-scratch-def.json --alias circle_build_$CIRCLE_BUILD_NUM --duration-days 7 --set-default

      # ソースコードをScratch Orgにプッシュ
      - run:
          name: Push Source to Scratch Org
          command: |
            sf project deploy start --target-org circle_build_$CIRCLE_BUILD_NUM

      # Apexテストを実行
      - run:
          name: Run Apex Tests
          command: |
            mkdir -p ~/junit
            sf apex run test --output-dir ~/junit --result-format junit --target-org circle_build_$CIRCLE_BUILD_NUM

      # テスト結果を保存
      - store_test_results:
          path: ~/junit

      # Scratch Orgを削除
      - run:
          name: Delete Scratch Org
          command: |
            sf org delete scratch --target-org circle_build_$CIRCLE_BUILD_NUM --no-prompt

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
