version: 2.1

jobs:
  yuka-birthday:
    docker:
      - image: salesforce/cli:latest-full
    steps:
      - checkout
      - run:
          name: "List all files in project"
          command: ls -R
      - run:
          name: "Authenticate to Salesforce Org"
          command: |
            sf force auth jwt grant -i $HUB_CONSUMER_KEY -f assets/server.key --username $HUB_SFDX_USER -d
      - run:
          name: "Deploy to Salesforce Org"
          command: |
            sf project deploy start -o SP
      - run:
          name: "Run LWC tests"
          command: |
            npm install
            npm test
      - run:
          name: "Run Apex tests"
          command: |
            sf force apex test run --result-format human --code-coverage
workflows:
  version: 2
  build-and-test:
    jobs:
      - yuka-birthday
